//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebAndAPI.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCAWebAndAPI.Web.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensatory time requested by Professional: (please complete the form, have it verified by the HR Unit before have it signed/approved by the Manager).
        /// </summary>
        public static string CompensatoryPrintText {
            get {
                return ResourceManager.GetString("CompensatoryPrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Edit Exit Procedure.
        /// </summary>
        public static string ErrorEditExitProcedure {
            get {
                return ResourceManager.GetString("ErrorEditExitProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable Edit Inactive PSA.
        /// </summary>
        public static string ErrorEditInActivePSA {
            get {
                return ResourceManager.GetString("ErrorEditInActivePSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional data that uses email {0} is not found. Please contact your IT Administrator..
        /// </summary>
        public static string ErrorProfessionalNotFound {
            get {
                return ResourceManager.GetString("ErrorProfessionalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant&apos;s Data is not sufficient to inserted as Professional Data, 
        ///
        ///Please complate the Applicant&apos;s data.
        /// </summary>
        public static string ErrorUpdateProfessional {
            get {
                return ResourceManager.GetString("ErrorUpdateProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation. It works!.
        /// </summary>
        public static string SuccessCommon {
            get {
                return ResourceManager.GetString("SuccessCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation! Your Adjustment Day-Off Balance data has successfully been created..
        /// </summary>
        public static string SuccessCreateAdjustmentDayOffBalance {
            get {
                return ResourceManager.GetString("SuccessCreateAdjustmentDayOffBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation {0}! Your application has successfully been submitted..
        /// </summary>
        public static string SuccessCreateApplicationData {
            get {
                return ResourceManager.GetString("SuccessCreateApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation {0}! Your Compensatory has successfully been submitted..
        /// </summary>
        public static string SuccessCreateCompensatoryData {
            get {
                return ResourceManager.GetString("SuccessCreateCompensatoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation {0}! Exit Procedure Data has successfully been created..
        /// </summary>
        public static string SuccessCreateExitProcedureData {
            get {
                return ResourceManager.GetString("SuccessCreateExitProcedureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation {0}! Your PSA data has successfully been created..
        /// </summary>
        public static string SuccessCreatePSAManagementData {
            get {
                return ResourceManager.GetString("SuccessCreatePSAManagementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}  has successfully been submitted..
        /// </summary>
        public static string SuccessCreateSPHLData {
            get {
                return ResourceManager.GetString("SuccessCreateSPHLData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your tax exemption data has successfully been submitted..
        /// </summary>
        public static string SuccessCreateTaxExemptionData {
            get {
                return ResourceManager.GetString("SuccessCreateTaxExemptionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation {0}! To download the printed version of your application. &lt;br/&gt;&lt;br/&gt;&lt;a href=&quot;{1}&quot; target=&quot;_blank&quot; class=&quot;btn btn-labeled btn-default&quot;&gt; &lt;span class=&quot;btn-label&quot;&gt;&lt;i class=&quot;fa fa-file&quot;&gt;&lt;/i&gt;&lt;/span&gt;Download File&lt;/a&gt;.
        /// </summary>
        public static string SuccessPrintApplicationData {
            get {
                return ResourceManager.GetString("SuccessPrintApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation! The application data of {0} has been set to {1}..
        /// </summary>
        public static string SuccessUpdateApplicationStatus {
            get {
                return ResourceManager.GetString("SuccessUpdateApplicationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation {0}! Exit Procedure Data has successfully been updated..
        /// </summary>
        public static string SuccessUpdateExitProcedure {
            get {
                return ResourceManager.GetString("SuccessUpdateExitProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation {0}! Your PSA data has successfully been updated..
        /// </summary>
        public static string SuccessUpdatePSAManagementData {
            get {
                return ResourceManager.GetString("SuccessUpdatePSAManagementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your tax exemption data has successfully been updated..
        /// </summary>
        public static string SuccessUpdateTaxExemptionData {
            get {
                return ResourceManager.GetString("SuccessUpdateTaxExemptionData", resourceCulture);
            }
        }
    }
}
