//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAWebAndAPI.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UrlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UrlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCAWebAndAPI.Service.Resources.UrlResource", typeof(UrlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/InputInterviewResultDetail.aspx?ID={1}&amp;manPos={2}.
        /// </summary>
        public static string AddInterviewInvitation {
            get {
                return ResourceManager.GetString("AddInterviewInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Adjustment%20DayOff%20Balance/AllItems.aspx.
        /// </summary>
        public static string AdjustmentDayOffBalanceList {
            get {
                return ResourceManager.GetString("AdjustmentDayOffBalanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Adjustment/AllItems.aspx.
        /// </summary>
        public static string AdjustmentList {
            get {
                return ResourceManager.GetString("AdjustmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists/Application.
        /// </summary>
        public static string ApplicationData {
            get {
                return ResourceManager.GetString("ApplicationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/DispForm.aspx?ID={1}.
        /// </summary>
        public static string ApplicationDisplayByID {
            get {
                return ResourceManager.GetString("ApplicationDisplayByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Application%20Documents/Forms/AllItems.aspx#InplviewHashc902afed-7be4-4799-9502-1818597c2223=FilterField1%3Dapplication%255Fx003a%255FID-FilterValue1%3D{1}.
        /// </summary>
        public static string ApplicationDocumentByID {
            get {
                return ResourceManager.GetString("ApplicationDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Asset%20Acquisition/AllItems.aspx.
        /// </summary>
        public static string AssetAcquisition {
            get {
                return ResourceManager.GetString("AssetAcquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Asset%20Assignment/AllItems.aspx.
        /// </summary>
        public static string AssetAssignment {
            get {
                return ResourceManager.GetString("AssetAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Asset%20Disposal/AllItems.aspx.
        /// </summary>
        public static string AssetDisposal {
            get {
                return ResourceManager.GetString("AssetDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Asset%20Loan%20Return/AllItems.aspx.
        /// </summary>
        public static string AssetLoanAndReturn {
            get {
                return ResourceManager.GetString("AssetLoanAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/AssetMaster/AllItems.aspx.
        /// </summary>
        public static string AssetMaster {
            get {
                return ResourceManager.GetString("AssetMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Asset%20Transfer/AllItems.aspx.
        /// </summary>
        public static string AssetTransfer {
            get {
                return ResourceManager.GetString("AssetTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Compensatory%20Request.
        /// </summary>
        public static string Compensatory {
            get {
                return ResourceManager.GetString("Compensatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/CompensatoryRequest/AllItems.aspx.
        /// </summary>
        public static string Compensatorylist {
            get {
                return ResourceManager.GetString("Compensatorylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Application%20Documents/Forms/AllItems.aspx#InplviewHash4adbc69d-4587-40ad-8645-58b419984117=FilterField1%3Dapplication%255Fx003a%255FID-FilterValue1%3D45#InplviewHashc67ecdef-ac05-4183-9a2d-c3752821814c=FilterField1%3Dapplication%255Fx003a%255FID-FilterValue1%3D{1}.
        /// </summary>
        public static string CVDocumentByID {
            get {
                return ResourceManager.GetString("CVDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Exit%20Procedure.
        /// </summary>
        public static string ExitProcedure {
            get {
                return ResourceManager.GetString("ExitProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/ExitProcedureDocuments/Forms/AllItems.aspx#InplviewHash8089e8d5-b941-4a0c-9d8a-9be53d040f76=FilterField1%3Dexitprocedureid-FilterValue1%3D{1}.
        /// </summary>
        public static string ExitProcedureDocumentByID {
            get {
                return ResourceManager.GetString("ExitProcedureDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ExitProcedureDocuments/Forms/AllItems.aspx#InplviewHash8089e8d5-b941-4a0c-9d8a-9be53d040f76=FilterField1%3DID-FilterValue1%3D25.
        /// </summary>
        public static string ExitProcedureExitInterviewForm {
            get {
                return ResourceManager.GetString("ExitProcedureExitInterviewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ExitProcedureDocuments/Forms/AllItems.aspx#InplviewHash8089e8d5-b941-4a0c-9d8a-9be53d040f76=FilterField1%3DID-FilterValue1%3D24.
        /// </summary>
        public static string ExitProcedureNonDisclosureAgreement {
            get {
                return ResourceManager.GetString("ExitProcedureNonDisclosureAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/SPHL%20Data/AllItems.aspx.
        /// </summary>
        public static string FINEventBudget {
            get {
                return ResourceManager.GetString("FINEventBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/OutstandingAdvance/AllItems.aspx.
        /// </summary>
        public static string FINOutstandingAdvance {
            get {
                return ResourceManager.GetString("FINOutstandingAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Tax%20Exemption%20Income%20Documents/Forms/AllItems.aspx#InplviewHash5093bda1-84bf-4cad-8652-286653d6a83f=FilterField1%3Dpsa%255Fx003a%255FID-FilterValue1%3D{1}.
        /// </summary>
        public static string FINPettyCashReplenishment {
            get {
                return ResourceManager.GetString("FINPettyCashReplenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/SPHL%20Data/AllItems.aspx.
        /// </summary>
        public static string FINSPHL {
            get {
                return ResourceManager.GetString("FINSPHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/SPHL%20Data/AllItems.aspx.
        /// </summary>
        public static string FINTaxReimbursement {
            get {
                return ResourceManager.GetString("FINTaxReimbursement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/InsuranceClaim.
        /// </summary>
        public static string InsuranceClaim {
            get {
                return ResourceManager.GetString("InsuranceClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/Interviewlistdata.aspx?POSID={1}.
        /// </summary>
        public static string InterviewDataList {
            get {
                return ResourceManager.GetString("InterviewDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/InputInterviewResult.aspx?ID={1}&amp;POS={2}.
        /// </summary>
        public static string InterviewInputResult {
            get {
                return ResourceManager.GetString("InterviewInputResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/Interviewlist.aspx?POSID={1}.
        /// </summary>
        public static string InterviewList {
            get {
                return ResourceManager.GetString("InterviewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/InterviewPanellist.aspx?POSID={1}.
        /// </summary>
        public static string InterviewPanelList {
            get {
                return ResourceManager.GetString("InterviewPanelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Location%20Master/AllItems.aspx.
        /// </summary>
        public static string LocationMaster {
            get {
                return ResourceManager.GetString("LocationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Manpower%20Requisition%20Documents/Forms/AllItems.aspx#InplviewHashb4cf8d69-0910-4645-ae07-01534b9b8c4a=FilterField1%3Dmanpowerrequestid-FilterValue1%3D{1}.
        /// </summary>
        public static string ManpowerDocumentByID {
            get {
                return ResourceManager.GetString("ManpowerDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists/Manpower%20Requisition.
        /// </summary>
        public static string ManpowerRequisition {
            get {
                return ResourceManager.GetString("ManpowerRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/MonthlyFee.
        /// </summary>
        public static string MonthlyFee {
            get {
                return ResourceManager.GetString("MonthlyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/PerformanceEvaluation.
        /// </summary>
        public static string PerformanceEvaluation {
            get {
                return ResourceManager.GetString("PerformanceEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/PerformancePlan.
        /// </summary>
        public static string PerformancePlan {
            get {
                return ResourceManager.GetString("PerformancePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists/Petty%20Cash%20Payment%20Voucher/AllItems.aspx.
        /// </summary>
        public static string PettyCashPaymentVoucher {
            get {
                return ResourceManager.GetString("PettyCashPaymentVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Petty%20Cash%20Payment%20Voucher%20Documents/Forms/AllItems.aspx#InplviewHash5093bda1-84bf-4cad-8652-286653d6a83f=FilterField1%3Dpsa%255Fx003a%255FID-FilterValue1%3D{1}.
        /// </summary>
        public static string PettyCashPaymentVoucherDocumentByID {
            get {
                return ResourceManager.GetString("PettyCashPaymentVoucherDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/Location%20Master.
        /// </summary>
        public static string PlaceMaster {
            get {
                return ResourceManager.GetString("PlaceMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists/Professional Master.
        /// </summary>
        public static string Professional {
            get {
                return ResourceManager.GetString("Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/Professional%20Data.aspx.
        /// </summary>
        public static string ProfessionalData {
            get {
                return ResourceManager.GetString("ProfessionalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Professional%20Master/DispForm_Custom.aspx?ID={1}.
        /// </summary>
        public static string ProfessionalDisplayByID {
            get {
                return ResourceManager.GetString("ProfessionalDisplayByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/Professional%20Performance%20Evaluation%20Approver.aspx.
        /// </summary>
        public static string ProfessionalPerformanceEvaluationApprover {
            get {
                return ResourceManager.GetString("ProfessionalPerformanceEvaluationApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/Professional%20Performance%20Evaluation%20HR.aspx.
        /// </summary>
        public static string ProfessionalPerformanceEvaluationHR {
            get {
                return ResourceManager.GetString("ProfessionalPerformanceEvaluationHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/ProfessionalPerformancePlan.
        /// </summary>
        public static string ProfessionalPerformancePlan {
            get {
                return ResourceManager.GetString("ProfessionalPerformancePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/Professional%20Perfromance%20Plan%20Approver.aspx.
        /// </summary>
        public static string ProfessionalPerformancePlanApprover {
            get {
                return ResourceManager.GetString("ProfessionalPerformancePlanApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /SitePages/Professional%20Perfromance%20Plan%20HR.aspx.
        /// </summary>
        public static string ProfessionalPerformancePlanHR {
            get {
                return ResourceManager.GetString("ProfessionalPerformancePlanHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/ProfessionalPerformanceEvaluation.
        /// </summary>
        public static string ProfessionalPerfromanceEvaluation {
            get {
                return ResourceManager.GetString("ProfessionalPerfromanceEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists/PSA.
        /// </summary>
        public static string PSAManagement {
            get {
                return ResourceManager.GetString("PSAManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/PSA%20Documents/Forms/AllItems.aspx#InplviewHash093fad79-4ce0-43c1-8824-1b429d747e81=FilterField1%3Dpsa%255Fx003a%255FID-FilterValue1%3D{1}.
        /// </summary>
        public static string PSAManagementDocumentByID {
            get {
                return ResourceManager.GetString("PSAManagementDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists/Requisition%20Note/AllItems.aspx.
        /// </summary>
        public static string RequisitionNote {
            get {
                return ResourceManager.GetString("RequisitionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Requisition%20Note%20Documents/Forms/AllItems.aspx#InplviewHash5093bda1-84bf-4cad-8652-286653d6a83f=FilterField1%3Dpsa%255Fx003a%255FID-FilterValue1%3D{1}.
        /// </summary>
        public static string RequisitionNoteDocumentByID {
            get {
                return ResourceManager.GetString("RequisitionNoteDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/SCA%20Voucher%20Documents/Forms/AllItems.aspx?FilterField1=SCA_x0020_Voucher_x003a_ID&amp;FilterValue1={1}.
        /// </summary>
        public static string SCAVoucherDocumentByID {
            get {
                return ResourceManager.GetString("SCAVoucherDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/ShortlistREQ.aspx?POSID={1}.
        /// </summary>
        public static string ShortlistEmailLinkHR {
            get {
                return ResourceManager.GetString("ShortlistEmailLinkHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/DispForm.aspx?ID={1}.
        /// </summary>
        public static string ShortlistEmailLinkInterview {
            get {
                return ResourceManager.GetString("ShortlistEmailLinkInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/Interviewlistdata.aspx?POSID={1}.
        /// </summary>
        public static string ShortlistEmailLinkREQ {
            get {
                return ResourceManager.GetString("ShortlistEmailLinkREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Lists/Application/ShortlistInterviewPanel.aspx?POSID={1}.
        /// </summary>
        public static string ShortlistInterviewPanel {
            get {
                return ResourceManager.GetString("ShortlistInterviewPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/SPHL%20Documents/Forms/AllItems.aspx?groupBy=&amp;FilterField1=SPHL_x003a_ID&amp;FilterValue1={1}.
        /// </summary>
        public static string SPHLDocumentByID {
            get {
                return ResourceManager.GetString("SPHLDocumentByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lists/TaxExemptionData.
        /// </summary>
        public static string TaxExemptionData {
            get {
                return ResourceManager.GetString("TaxExemptionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/Tax%20Exemption%20Income%20Documents/Forms/AllItems.aspx#InplviewHash5093bda1-84bf-4cad-8652-286653d6a83f=FilterField1%3Dpsa%255Fx003a%255FID-FilterValue1%3D{1}.
        /// </summary>
        public static string TaxExemptionIncomeDocumentByID {
            get {
                return ResourceManager.GetString("TaxExemptionIncomeDocumentByID", resourceCulture);
            }
        }
    }
}
